// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgressHub.Data;

#nullable disable

namespace ProgressHub.Data.Migrations
{
    [DbContext(typeof(ProgressHubDbContext))]
    partial class ProgressHubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("ProgressHub.Core.Models.DailyLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumedCalories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumedCarbs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumedFats")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsumedProteins")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("DailyLog");
                });

            modelBuilder.Entity("ProgressHub.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("HeightInCm")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TargetCalories")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetCarbsGrams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetFatsGrams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetProteinGrams")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserRole")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProgressHub.Core.Models.DailyLog", b =>
                {
                    b.HasOne("ProgressHub.Core.Models.User", "User")
                        .WithMany("DailyLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ProgressHub.Core.Models.User", b =>
                {
                    b.Navigation("DailyLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
